services:
  - type: web
    name: pw-quantum
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PW_API
        sync: false
      - key: JWT_ACCESS_EXPIRES
        value: "15"
      - key: JWT_REFRESH_EXPIRES_DAYS
        value: "30"
      - key: LOG_CHANNEL_ID
        sync: false
      - key: REFRESH_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_NAME
        value: "PW Quantum"
      - key: JWT_ACCESS_EXPIRES_SECONDS
        value: "1296000"
      - key: NEXT_PUBLIC_TG
        value: "https://t.me/PwQuantum"
      - key: SHORTNER_TOKEN_SECRET
        sync: false
      - key: NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT_ID
        sync: false
